name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_test:
    name: Build and Test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    timeout-minutes: 30
    steps:
    - name: Checkout laps
      uses: actions/checkout@v2

    - name: Build
      run: cargo check && cargo check --all-features

    - name: Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Test
      run: cargo test --workspace

  build_examples:
    name: Build Examples
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    timeout-minutes: 30
    strategy:
      matrix:
        example-name: ['clike']

    steps:
    - name: Checkout laps
      uses: actions/checkout@v2

    - name: Build
      run: cargo check --example ${{matrix.example-name}} --features macros
